workflows:
  android-workflow:
    name: Build Kotlin Android App
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Use correct Java version
        script: |
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          java -version
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
